GEMINI_API_KEY = "AIzaSyALgzgLQTX6avknNUzknLxSgmTggTJfTUg"
ELEVENLABS_API_KEY = "sk_0048770c4dd23670baac2de2cd6f616e2856935e8297be5f"
HEYGEN_API_KEY = "ZWIzM2VhOTQzYjZiNDg5OWE2MmQ2NWNhZjJmNDJjMTYtMTc1MzEwMzUyMQ=="
