GEMINI_API_KEY = "AIzaSyA9VPlM-MSjDYytvd4J2wQ_f1nc5Tmd7dk"
ELEVENLABS_API_KEY = "sk_11bac39a10fe50c34f1e5f11abdcae05780e0369489d918d"
HEYGEN_API_KEY = "YjU1NzFkMTk4YmQ5NDkwNDlhM2U4MGFmY2Q2NjlkNjQtMTc1MzI2ODUwOQ=="
