# .streamlit/secrets.toml
# Configuration file for Streamlit deployment with HeyGen
# Add your API keys here (DO NOT commit this file to public repositories)

# Required: Google Gemini API Key
# Get it from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY = "AIzaSyCZ5EKT2Ouh8Fhu3rAoB9MwquvNC5vmUqs"

# Required: HeyGen API Key for realistic talking avatars  
# Get it from: https://app.heygen.com/account-settings
# HeyGen offers reliable avatar generation with excellent uptime
HEYGEN_API_KEY = "ZWIzM2VhOTQzYjZiNDg5OWE2MmQ2NWNhZjJmNDJjMTYtMTc1MzEwMzUyMQ=="

# Optional: ElevenLabs API Key for premium natural voices
# Get it from: https://elevenlabs.io/speech-synthesis
# If not provided, system will use browser TTS as fallback
ELEVENLABS_API_KEY = "sk_c8da14020dfcad23237e8e2b3f9548ea48e5f344de27e604"

# Additional settings (optional)
[settings]
# Enable debug mode for development
DEBUG_MODE = false

# Default avatar choice
DEFAULT_AVATAR = "sophia"

# Voice settings
DEFAULT_VOICE_SPEED = 1.0
DEFAULT_VOICE_PITCH = 1.0

# ================================
# SETUP INSTRUCTIONS:
# ================================
# 
# 1. GEMINI API (Required - Free tier available):
#    - Go to https://makersuite.google.com/app/apikey
#    - Create a new API key
#    - Replace with your actual key above
#
# 2. HEYGEN API (Required for realistic avatars):
#    - Go to https://app.heygen.com/account-settings
#    - Sign up for free account (includes free credits)
#    - Navigate to API Keys section
#    - Generate new API key and copy it
#    - Replace with your actual key above
#
# 3. ElevenLabs API (Optional for premium voices):
#    - Go to https://elevenlabs.io/speech-synthesis
#    - Sign up for account (free tier available)
#    - Get API key from settings
#    - Replace with your actual key above
#
# 4. For Streamlit Cloud deployment:
#    - Go to your Streamlit Cloud app settings
#    - Navigate to "Secrets" section
#    - Copy the content of this file (with real API keys)
#    - Paste into the secrets text area
#
# ================================
# SECURITY NOTES:
# ================================
# 
# - NEVER commit this file with real API keys to version control
# - Add .streamlit/secrets.toml to your .gitignore file
# - Use environment variables in production
# - Regularly rotate your API keys for security
# - Monitor API usage to detect unauthorized access

# ================================
# WHY HEYGEN INSTEAD OF D-ID:
# ================================
# 
# - More reliable API with 99%+ uptime
# - Better customer support and documentation
# - No server-side circular reference errors
# - Faster video generation times
# - More stable authentication system
# - Better pricing and free tier options
