GEMINI_API_KEY = "AIzaSyDZCG1cuKAa0IOqUdGCbFWIemWjErUiSeU"
ELEVENLABS_API_KEY = "sk_da2743844b74d8828b3d7d24c65984b95a55a71886ad12b3"
HEYGEN_API_KEY = "YjU1NzFkMTk4YmQ5NDkwNDlhM2U4MGFmY2Q2NjlkNjQtMTc1MzI2ODUwOQ=="
