# Add your Gemini API key here
# Get it from: https://makersuite.google.com/app/apikey

GEMINI_API_KEY = "AIzaSyBwg8-35yvKImEatfrm3oCk-Z4lWopTq20"

# Optional: Add other API keys if you want to use premium services later
ELEVENLABS_API_KEY = "sk_c8da14020dfcad23237e8e2b3f9548ea48e5f344de27e604"

# D-ID offers free credits for testing
DID_API_KEY = "d2luYW11bmFkYTUzQGdtYWlsLmNvbQ:e98s0LfHcM-xhnHi00eEK"
